clean: ch3-clean ch4-clean
	@rm -rf \
	*.aux \
	\#*\# \
	*.log \
	*.bbl \
	*.out \
	*~ \
	*.pdf \
	*.dvi \
	*.synctex.gz \
	*.blg \
	*.toc \
	*.lot \
	*.fls \
	*.rip \
	*.fdb_latexmk \
	*.xcp \
	*.xoj \
	*.lof \
	*.brf \
	*.diagnose \
	*.kaux \
	.\#*.tex
